title: HealthCare.gov Styleguide
baseurl: 
canonical-url: https://styleguide.healthcare.gov
permalink: /:categories/:title
markdown: rdiscount
highlighter: null
encoding: utf-8
#exclude : ['sass', 'config.rb', 'README.md']
exclude:
  - .gitignore
  - README.md
  - privatekey.p12
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitattributes
  - Gruntfile.js
  - package.json
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'Espa√±ol'
    value: 'es'
